// <auto-generated />
using FPT.BOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPT.Migrations
{
    [DbContext(typeof(FPTBusinessContext))]
    [Migration("20241110090631_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPTBussiness.BOs.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("NameProject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            NameProject = "Library System"
                        },
                        new
                        {
                            ProjectID = 2,
                            NameProject = "Travel Website"
                        },
                        new
                        {
                            ProjectID = 3,
                            NameProject = "Fashion Website"
                        });
                });

            modelBuilder.Entity("FPTBussiness.BOs.ProjectDetails", b =>
                {
                    b.Property<int>("ProjectDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectDetailID"));

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("RoleStaff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("ProjectDetailID");

                    b.ToTable("ProjectDetails");

                    b.HasData(
                        new
                        {
                            ProjectDetailID = 1,
                            NumberOfHours = 120,
                            ProjectID = 1,
                            RoleStaff = "Manager",
                            StaffID = 1
                        },
                        new
                        {
                            ProjectDetailID = 2,
                            NumberOfHours = 100,
                            ProjectID = 2,
                            RoleStaff = "Developer",
                            StaffID = 7
                        },
                        new
                        {
                            ProjectDetailID = 3,
                            NumberOfHours = 80,
                            ProjectID = 3,
                            RoleStaff = "Design",
                            StaffID = 8
                        });
                });

            modelBuilder.Entity("FPTBussiness.BOs.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("AddressStaff")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffID");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            AccountID = 2,
                            AddressStaff = "15 Quang Trung Da Nang",
                            FirstName = "Nguyen",
                            Gender = "Male",
                            LastName = "An"
                        },
                        new
                        {
                            StaffID = 2,
                            AccountID = 3,
                            AddressStaff = "25 Hoang Tieu Da Nang",
                            FirstName = "Le",
                            Gender = "FeMale",
                            LastName = "Bao"
                        },
                        new
                        {
                            StaffID = 3,
                            AccountID = 4,
                            AddressStaff = "30 Le Duan Da Nang",
                            FirstName = "Tran",
                            Gender = "FeMale",
                            LastName = "Cuong"
                        });
                });

            modelBuilder.Entity("FPTBussiness.BOs.UserAccount", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountID");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            Password = "admin",
                            Role = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            AccountID = 2,
                            Password = "user1",
                            Role = 0,
                            UserName = "user1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
